server:
  port: 10100


feign:
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        timeout:
          #如果enabled设置为false，则请求超时交给ribbon控制
          enabled: false
        isolation:
          thread:
            timeoutInMilliseconds: 10000

  #请求处理的超时时间
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000


spring:
  datasource:
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 10000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-init-sql: set names utf8mb4
    type: com.zaxxer.hikari.HikariDataSource
    dynamic:
      primary: master #默认数据库（主库）
      datasource:
        master: #自定义链接名称
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://192.168.0.123:3306/wande_sys_uaa?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2b8
          username: root
          password: 123456
        second: #自定义链接名称
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://192.168.0.123:3306/wande_sys_uaa?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2b8
          username: root
          password: 123456
  cloud:
    loadbalancer:
      retry:
        enabled: true

  # redis \\
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    database: 0
    jedis:
      pool:
        max-active: 8
        max-wait: 1
        min-idle: 0
        max-idle: 8
    timeout: 300000
  # redis //

mybatis-plus:
  mapper-locations: classpath*:/mapper/*/*Mapper.xml
  # 实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.wande.*.entity
  # type-enums-package: com.whatech.*.entity.enums
  global-config:
    # 数据库相关配置
    db-config:
      # 主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: uuid
      # 字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: not-empty
      # 默认查询时进行模糊查询
      # column-like: true
      # 数据库大写下划线转换
      # capital-mode: true
      # 设置逻辑删除字段的值为1
      # logic-delete-value: 1
      # 设置不逻辑删除的值为0
      # logic-not-delete-value: 0
      # db-type: mysql
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    # 下面这句会将SQL语句完整的输出至控制台
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

management:
  endpoints:
    web:
      exposure:
        include: "*"

# 部门编码、区域编码会用到：A0001A0002A0003
youBianCodeUtil:
  num-length: 4
  zhanwei-length: 5


wande:
  sys:
    system-key: bk
